query ResearchPosts(
  $pagination: PaginationArg
  $tags: [String]
  $coins: [String]
  $isPRO: Boolean
  $tab: String
) {
  posts(
    pagination: $pagination
    filters: {
      tags: { name: { in: $tags } }
      isPRO: { eq: $isPRO }
      tabs: { tabName: { in: [$tab] }}
      coins: { coinGeckoID: { in: $coins } }
    }
    sort: "publishedAt:desc"
  ) {
    meta {
      pagination {
        total
        pageCount
      }
    }
    data {
      id
      attributes {
        slug
        title
        tags {
          data {
            attributes {
              name
            }
          }
        }
        summary
        publishedAt
        banner {
          data {
            attributes {
              url
              alternativeText
            }
          }
        }
        readTimeInMinutes
        writers {
          data {
            id
            attributes {
              name
              profilePicture {
                data {
                  attributes {
                    url
                    alternativeText
                  }
                }
              }
            }
          }
        }
        highlighted
        isPRO
      }
    }
  }
  tags {
    data {
      attributes {
        name
      }
    }
  }
  tabs {
    data {
      attributes {
        tabName
        position
      }
    }
  }
  coins {
    data {
      attributes {
        image {
          data {
            attributes {
              alternativeText
              url
            }
          }
        }
        coinGeckoID
        name
        symbol
      }
    }
  }
}