query PoolInfo($id: ID!, $day: Int!) {
  pool(id: $id) {
    # information aHYPE
    id
    name
    decimals
    symbol
    price_usd
    logo
    founded_by
    # pool token information
    underlying_assets(orderBy: weight_normalized, orderDirection: desc) {
      balance # token balance in pool
      weight_normalized # current allocation in the pool between 0 and 1
      weight_goal_normalized # expected allocation in the pool between 0 and 1
      # token information
      token {
        id
        logo
        name
        decimals
        symbol
        wraps {
          logo
        }
      }
    }
    now: price_candles(
      where: { base: "usd", period: 3600 }
      orderBy: timestamp
      orderDirection: desc
      first: 1
    ) {
      timestamp
      close
    }
    day: price_candles(
      where: { base: "usd", period: 3600, timestamp_gt: $day }
      orderBy: timestamp
      first: 1
    ) {
      timestamp
      close
    }
    weight_goals(orderBy: end_timestamp, orderDirection: desc, first: 2) {
      start_timestamp
      end_timestamp
      weights(orderBy: weight_normalized, orderDirection: desc) {
        asset {
          token {
            id
          }
        }
        weight_normalized
      }
    }
  }
}
